# Utiliza la imagen oficial de Neo4j
FROM neo4j:latest

# Expone los puertos necesarios
EXPOSE 7474 7687

# Configura las credenciales de acceso por defecto (puedes cambiarlas según tu necesidad)
ENV NEO4J_AUTH=neo4j/password

# Comando para iniciar Neo4j
CMD ["neo4j"]
