version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8050:8050"
    volumes:
      - ./frontend:/app
      - ./VulnhunterAI/output:/app/data
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - application

  application:
    build:
      context: ./VulnhunterAI
    container_name: vulnhunterai_container
    volumes:
      - ./VulnhunterAI:/home/user
    ports:
      - "5001:5001"
   #command: pip install -r requirements.txt
