version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8050:8050"
    volumes:
      - ./frontend:/app
    depends_on:
      - application
    networks:
      - my_network

  application:
    build:
      context: ./VulnHunterAI
    ports:
      - "5000:5000"
    volumes:
      - ./VulnHunterAI:/home/user
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1

  neo4j:
    build:
      context: ./database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./database:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

