version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8050:8050"
    volumes:
      - ./frontend:/app
    depends_on:
      - application
    networks:
      - my_network  

  neo4j:
    build:
      context: ./databases/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./databases/neo4j:/data
    networks:
      - my_network

  application:
    build:
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/user
    depends_on:
      - redis
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    build:
      context: ./databases/redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
